spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/viajes                      
spring.datasource.username: root
spring.datasource.password: root
spring:
  application:
    name: servicio-vuelos
server:
  port: 9000
  servlet:
    context-path: /vuelos
eureka:
  instance:
    ip-address: 10.2.4.24
    prefer-ip-address: true
    instance-id: 10.2.4.24:9000    
  client:    
    serviceUrl:
      defaultZone: http://10.2.4.100:8761/eureka
