spring:
  application:
    name: servicio-hoteles
server:
  port: 8002
  servlet:
    context-path: /hoteles
eureka:
  instance:
    ip-address: 10.2.4.23
    prefer-ip-address: true
    instance-id: 10.2.4.23:8002    
  client:    
    serviceUrl:
      defaultZone: http://10.2.4.24:8761/eureka
