spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://localhost:3306/viajes                      
    username: root
    password: root	
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring:
  application:
    name: servicio-vuelos
server:
  port: 9000
  servlet:
    context-path: /vuelos
eureka:
  instance:
    ip-address: 10.2.4.24
    prefer-ip-address: true
    instance-id: 10.2.4.24:9000    
  client:    
    serviceUrl:
      defaultZone: http://10.2.4.100:8761/eureka
