server:
  port: 9001
  servlet:
    context-path: /vuelos
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.41:3306/viajes 
    username: root
    password: root
eureka:
  instance:
    ip-address: 192.168.1.41
    prefer-ip-address: true
    instance-id: 192.168.1.41:9001    
  client:    
    serviceUrl:
      defaultZone: http://192.168.1.41:8761/eureka
