servicio.cliente.url: http://servicio-vuelos/vuelos  
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/viajes                      
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring:
  application:
    name: servicio-reservas
server:
  port: 8001
  servlet:
    context-path: /reservas
eureka:
  instance:
    ip-address: 10.2.4.25
    prefer-ip-address: true
    instance-id: 10.2.4.25:8001    
  client:    
    serviceUrl:
      defaultZone: http://10.2.4.24:8761/eureka
